### PR TITLE
refactor: Un-submodule bundestag.io-api/

### PR DESCRIPTION
**Pull request by roschaefer**
## Pullrequest
This will
* remove `bundestag.io-api/` submodule while preserving git history
* replace former Github workflow to push docker image
  * docker images tags are pushed based on several conditions (branch, tags, releases)
  * docker tags will *not* be overwritten (except for same branch etc.)
  * docker images are pushed to [dockerhub](https://hub.docker.com/repository/docker/democracy/bundestag.io) - and not to Github's registry

### Issues
Mainly this is to improve maintainability. If you have one team, one release cycle and one code base, git submodules are not a good idea. They won't help but increase complexity.

### Repositories Affected

- [x] bundestag.io (removed)
- [ ] bundestag.io-admin
- [ ] client
- [ ] democracy-app.de
- [ ] democracy-app.de-api
- [ ] democracy-app.de-admin
- [ ] democracy-deutschland.de
- [ ] docu
- [ ] elasticsearch

### How2Test
Read the tutorial I followed to remove a [submodule while preserving the history](https://medium.com/walkme-engineering/how-to-merge-a-git-submodule-into-its-main-repository-d83a215a319c).

Check the build server for new tests. Clone the repository and follow the [README](https://github.com/demokratie-live/democracy-development/blob/unsubmodule/bundestag.io-api/README.md).

### Todo
- [ ] Update kubernetes configuration (I suggest to do this in another PR)

### CODE REVIEW

**Comment by roschaefer** [comment]
@ManAnRuck 

swappy-20210527_232143

**Review by ManAnRuck — DISMISSED** [review]
🤩

**Comment by roschaefer** [comment]
@ManAnRuck feel free to hit "Approve" or "Request changes"

**Review by ManAnRuck — APPROVED** [review]

**Comment by roschaefer** [comment]
swappy-20210602_205755

**Pull request merged**
